ifeq "$(origin SDK_ROOT)" "undefined"
$(error SDK_ROOT is undefined)
endif


SRC_FILES += $(SDK_ROOT)/common/device_manager.c
SRC_FILES += $(SDK_ROOT)/common/discovery_threads.c
SRC_FILES += $(SDK_ROOT)/common/network.c


SRC_FILES += $(SDK_ROOT)/common/client.c
SRC_FILES += $(SDK_ROOT)/common/cmd_parser.c
SRC_FILES += $(SDK_ROOT)/common/server.c
SRC_FILES += $(SDK_ROOT)/common/utils.c
